import type { FeedGroup } from '../app/types/feed'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region 经常联系
	{
		name: '经常联系',
		desc: '经常联系的朋友们',
		entries: [
			{
				author: '纸鹿本鹿',
				sitenick: '摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://www.zhilu.site/icon.png',
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-05-20',
				comment: '我的前端老师',
			},
			{
				author: 'minc_nice_100',
				sitenick: '土拨鼠',
				title: 'Ited Blog',
				desc: 'You are good enough.',
				link: 'https://www.itedev.com/',
				feed: 'https://www.itedev.com/atom.xml',
				icon: 'https://static.itedev.com/favicon.ico',
				avatar: 'https://avatars.githubusercontent.com/u/100515973?s=40&v=4',
				archs: ['Jekyll', 'Cloudflare'],
				date: '2026-06-05',
				comment: '一只很厉害的运维',
			},
			{
				author: 'Makabaka1880',
				sitenick: '鲤鱼',
				title: 'Teal Blog',
				desc: '',
				link: 'https://blog.makabaka1880.xyz/',
				feed: '',
				icon: 'https://blog.makabaka1880.xyz/favicon.ico',
				avatar: 'https://blog.makabaka1880.xyz/favicon.ico',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2026-06-05',
				comment: '我帮忙搞的博客',
			},
			{
				author: 'EastWind',
				title: 'EastWind',
				sitenick: '东风',
				desc: '东风不与周郎便，铜雀春深锁二乔',
				link: 'https://blog.1wind.cn/',
				feed: 'https://blog.1wind.cn/atom.xml',
				icon: getGithubIcon('WindyDante'),
				avatar: getGithubAvatar('WindyDante'),
				archs: ['Astro', 'Vercel'],
				date: '2026-06-05',
				comment: '',
			},
			{
				author: '皓然',
				title: '皓然小站',
				sitenick: '小站',
				desc: '分享生活和技术的点滴',
				link: 'https://blog.horonlee.com/',
				feed: 'https://blog.horonlee.com/atom.xml',
				icon: 'https://bu.dusays.com/2023/02/05/63dfc7f2ced91.png',
				avatar: getOicqAvatar('1269024821'),
				archs: ['Vue', 'EdgeOne'],
				date: '2026-04-26',
				comment: 'Ech0群里认识的神秘初创公司创业者',
			},
			{
				author: 'AirTouch',
				sitenick: 'の小站',
				title: 'AirTouchの小站',
				desc: '分享技术、生活、思考。',
				link: 'https://www.xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/favicon.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2026-04-26',
				comment: '神秘小初中生',
			},
			{
				author: 'Liushen',
				sitenick: '清羽飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/info/avatar.ico',
				avatar: getOicqAvatar('3162475700'),
				archs: ['Astro', 'EdgeOne', '服务器'],
				date: '2026-06-05',
				comment: '大佬大佬',
			},
			{
				author: '米葱苓sama',
				sitenick: '小筑',
				title: '葱苓小筑',
				desc: '风带来了故事的种子，时间使其发芽。',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/atom.xml',
				icon: 'https://blog.ciraos.top/favicon.ico',
				avatar: getOicqAvatar('1298926752'),
				archs: ['Next.js'],
				date: '2026-06-05',
				comment: '',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
